name: jargon-webhooks

on:
  repository_dispatch:
    types: [jargon_onSnapshot]

jobs:
  validate-jargon-artifacts:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Validate Jargon Artefacts
        uses: ./.github/actions/validate-jargon-artefacts
        with:
          jargon-webhook-payload: ${{ toJSON(github.event.client_payload) }}